name: CI
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Scrape Hacker News
        id: scrape
        uses: actions/github-script@v5
        with:
          script: |
            const fetch = require('node-fetch');
            const response = await fetch('https://news.ycombinator.com');
            const body = await response.text();
            core.setOutput('content', body);
      - name: Create new file
        run: echo "${{ steps.scrape.outputs.content }}" > ${{ steps.date.outputs.date }}.md
      - name: Commit new file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add daily Hacker News scrape"