name: Create Daily Hacker News Post
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Added a comment to force re-evaluation

jobs:
  create_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "formatted_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create _posts directory
        run: mkdir -p _posts

      - name: Create test post file
        run: echo "---\nlayout: post\ntitle: \"Test Post\"\ndate: ${{ steps.date.outputs.formatted_date }}\n---\n\nThis is a test post." > _posts/${{ steps.date.outputs.formatted_date }}-test-post.md

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: Add test post'
          file_pattern: _posts/*.md
